package uk.co.appoly.droid.s3upload.multipart.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity representing a multipart upload session.
 *
 * Stores all information needed to track, pause, resume, and recover
 * a multipart upload to S3.
 */
@Entity(
	tableName = "multipart_upload_sessions",
	indices = [
		Index(value = ["local_file_path"]),
		Index(value = ["status"])
	]
)
data class UploadSessionEntity(
	/** Local session ID (UUID generated by client) */
	@PrimaryKey
	@ColumnInfo(name = "session_id")
	val sessionId: String,

	/** AWS S3 multipart upload ID returned from initiate call */
	@ColumnInfo(name = "upload_id")
	val uploadId: String,

	/** Path to the local file being uploaded */
	@ColumnInfo(name = "local_file_path")
	val localFilePath: String,

	/** S3 file path/key where file will be stored */
	@ColumnInfo(name = "remote_file_path")
	val remoteFilePath: String,

	/** Original file name */
	@ColumnInfo(name = "file_name")
	val fileName: String,

	/** MIME type of the file */
	@ColumnInfo(name = "content_type")
	val contentType: String,

	/** Total file size in bytes */
	@ColumnInfo(name = "total_file_size")
	val totalFileSize: Long,

	/** Size of each chunk/part in bytes (minimum 5MB per S3) */
	@ColumnInfo(name = "chunk_size")
	val chunkSize: Long,

	/** Total number of parts to upload */
	@ColumnInfo(name = "total_parts")
	val totalParts: Int,

	/** Current status of the upload session */
	@ColumnInfo(name = "status")
	val status: UploadSessionStatus,

	/** API URL for initiating multipart upload */
	@ColumnInfo(name = "initiate_url")
	val initiateUrl: String,

	/** API URL for getting pre-signed URL for each part */
	@ColumnInfo(name = "presign_part_url")
	val presignPartUrl: String,

	/** API URL for completing multipart upload */
	@ColumnInfo(name = "complete_url")
	val completeUrl: String,

	/** API URL for aborting multipart upload */
	@ColumnInfo(name = "abort_url")
	val abortUrl: String,

	/** Timestamp when session was created */
	@ColumnInfo(name = "created_at")
	val createdAt: Long,

	/** Timestamp when session was last updated */
	@ColumnInfo(name = "updated_at")
	val updatedAt: Long,

	/** Last error message if failed */
	@ColumnInfo(name = "error_message")
	val errorMessage: String? = null,

	/** Number of retry attempts made */
	@ColumnInfo(name = "retry_count")
	val retryCount: Int = 0,

	/** Maximum number of retries allowed */
	@ColumnInfo(name = "max_retries")
	val maxRetries: Int = 3
)
